# Generated by Django 5.2.1 on 2025-07-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('Bites', 'Bites'), ('Brews', 'Brews')], max_length=10)),
                ('image', models.ImageField(upload_to='images/')),
                ('delete_status', models.IntegerField(choices=[(1, 'AVAILABLE'), (0, 'OUT OF STOCK')], default=1)),
            ],
        ),
    ]
