# Generated by Django 5.2.1 on 2025-07-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_charges_order_orderitem_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('staff', models.CharField(choices=[('Dining', 'Dining'), ('Kitchen', 'Kitchen')], max_length=10)),
                ('employment_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['staff', 'name'],
            },
        ),
    ]
