# Generated by Django 5.2.1 on 2025-07-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_payment_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
