# Generated by Django 5.2.1 on 2025-07-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_payment_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
