# Generated by Django 5.2.1 on 2025-07-07 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_payment_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='viewed',
        ),
    ]
