# Generated by Django 5.2.1 on 2025-07-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_remove_payment_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
