# Generated by Django 5.1.7 on 2025-07-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_payment_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
