# Generated by Django 5.1.7 on 2025-07-15 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0009_order_is_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_notified',
        ),
    ]
