# Generated by Django 5.2.1 on 2025-07-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0010_remove_order_is_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
