# Generated by Django 5.2.1 on 2025-09-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0011_order_is_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
