# Generated by Django 5.2.1 on 2025-09-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0012_payment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
