# Generated by Django 5.2.1 on 2025-09-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0013_employee_emp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phno',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
